# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import slack.models.keyvalue


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValuePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=240)),
                ('value', models.CharField(blank=True, db_index=True, max_length=240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyValueStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_namespace', models.CharField(blank=True, default='', max_length=255, unique=True)),
            ],
            bases=(slack.models.keyvalue.KeyValueStoreBase, models.Model),
        ),
        migrations.AddField(
            model_name='keyvaluepair',
            name='segment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='slack.KeyValueStore'),
        ),
    ]
